### ISSUE TITLE
Add margin-bottom after "About our tech talks"

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/talks#43]
I suggest to add margin-bottom after "About our tech talks" so that it detaches from the description text.

![image](https://cloud.githubusercontent.com/assets/2793551/26037778/36f9c75e-38fb-11e7-93cd-0e1a1e56f792.png)

**Comment by Serabe** [comment]
Title and content should be visually attached. Will be reviewed once we have a finished design for the landing.

**Comment by dpordomingo** [comment]
Is this still needed @vmarkovtsev @ricardobaeta ?

**Comment by dpordomingo** [comment]
@vmarkovtsev @ricardobaeta  I'll close it; feel free to reopen if it is still neede :D
