### ISSUE TITLE
Changes missing:

### ISSUE THREAD

**Issue by margaridagsl** [src-d/talks#7]
**Landing Page:**
- [x] Remove word 'rockstars'.
- [x] Think about better word for 'Register' --> Get your ticket?
- [x] Fix Mailchimp subscription form.
- [x] About section: add main paragraph.
- [x] About section: fix colors of pics.
- [ ] Fix size of pics.

**Schedule Page:**
- [x] Schedule talks even if not final.
- [x] Add talks abstract.

**Other:**
- [x] Fix Google loader.

**Comment by Serabe** [comment]
Closing. Superseded by #30.
