### ISSUE TITLE
Hard-coded links to images

### ISSUE THREAD

**Issue by smeruelo** [src-d/talks#77]
There are hard-coded links to images (`http://sourced.tech/img/logos/logo-blue.svg` at least, maybe more).

We are migrating soon this site to kubernetes and, when we do that, we'll force `HTTP` to `HTTPS`. Browsers will warn the user that some parts of the page are not secure, so please fix this.

**Comment by dpordomingo** [comment]
![image](https://user-images.githubusercontent.com/2437584/32323615-e92ea0d0-bfc8-11e7-9d72-488083c3c4b3.png)

**Comment by dpordomingo** [comment]
It was locally fixed, and merged into master in some minutes
![image](https://user-images.githubusercontent.com/2437584/32500097-a5cdacb8-c3d4-11e7-8833-c209fc15cdf2.png)
