### ISSUE TITLE
How're the css files being generated?

### ISSUE THREAD

**Issue by dpordomingo** [src-d/talks#83]
I'm trying to find the way how css are generated, but I couldn't.

I tried some things:

1. Check the [Makefile](https://github.com/src-d/talks/blob/master/Makefile) -> nope
2. Check the [README.md](https://github.com/src-d/talks/blob/master/README.md) -> it is only said how to create a new site, and work with images
3. Check each [talk/README.md](https://github.com/src-d/talks/blob/master/front-2017/README.md)
```bash
gem install bundler;
bundle install;
jekyll serve -w
```
CSS are not re-generated

4. I tried `bin/automated` -> nope
5. I tried with google, and found [a guy asking the same](https://github.com/gdg-x/zeppelin/issues/79); The maintainer answered pointing to the [wiki](https://github.com/gdg-x/zeppelin/wiki/Sass-development)
```bash
compass watch
    error main.scss (Line 5: Invalid CSS after "..."partials/base"": expected "{", was ";")
```
Compile error.

I tried to find why, and it seems that @serabe [removed compass](https://github.com/src-d/talks/commit/1af6aabff49c90aa7108ae45cea422ac84adcc7c) from the talks, but it was not provided the way to auto-generate the css.

So... I'd appreciate if someone could enlighten me a bit...

**Comment by Serabe** [comment]
It's jekyll doing it. Good luck finding how :$

**Comment by dpordomingo** [comment]
I found the problem.
@Serabe In case you're still interested in knowing how jekyll generates that css, you can see it the commit https://github.com/src-d/talks/commit/bbc68fd9368fcb8f4a9cc4d08cf26b55831cf9c2

It seems that Jekyll builds the `main.scss` located into the `css` directory instead of the `_sass` one. 
WTF? -> yes :(

The problem was caused after removing compass https://github.com/src-d/talks/pull/36 but not applying the fix in all talks/blueprint  https://github.com/src-d/talks/pull/37

**Comment by dpordomingo** [comment]
And documented by https://github.com/src-d/talks/pull/89
